mysql:
  host: localhost
  port: 3306
  config: "charset=utf8mb4&parseTime=True&loc=Local"
  db: 49_project
  user: root
  password: 1234
  log_level: dev
logger:
  level: info
  prefix: '[49_project]'
  director: log
  show-line: true
  log-in-console: true
system:
  host: localhost
  port: 8080
  env: release
jwt:
  secret: xxxxx
  expires: 12   # Token expiration time /hour
  issuer: "49_project"
redis:
  ip: localhost
  port: 6379
  password: 1234
  pool_size: 100
grpc:
  ip: localhost
  port: 8088
mq:
  ip: localhost
  port: 5672
  username: guest
  password: guest