mysql:
  host: 127.0.0.1
  port: 3306
  config: "charset=utf8mb4&parseTime=True&loc=Local"
  db: 49_project
  user: root
  password: 1234
  log_level: dev
logger:
  level: info
  prefix: '[49_project]'
  director: log
  show-line: true
  log-in-console: true
system:
  host: 127.0.0.1
  port: 8080
  env: release
jwt:
  secret: xxxxx
  expires: 12   # Token expiration time /hour
  issuer: "49_project"
redis:
  ip: 127.0.0.1
  port: 6379
  password: 1234
  pool_size: 100
grpc:
  ip: 127.0.0.1
  port: 8088
mq:
  ip: 127.0.0.1
  port: 5672
  username: guest
  password: guest
qi_niu:
  enable: true
  access_key: eV3Go_tP95TtjyR4J3Wj-pm6FZgtomx9fJov9tNp
  secret_key: 0N8lJPUuJWFvzFi854r5HgOjzxwDR-Gig1EkYTh9
  bucket: cxy-sing
  cdn: rygkmaqix.sabkt.gdipper.com
  zone: as0
  size: 5