// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.0
// source: data.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	FormatData_DoFormat_FullMethodName = "/proto.FormatData/DoFormat"
)

// FormatDataClient is the client API for FormatData service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FormatDataClient interface {
	DoFormat(ctx context.Context, in *Actionrequest, opts ...grpc.CallOption) (*Actionresponse, error)
}

type formatDataClient struct {
	cc grpc.ClientConnInterface
}

func NewFormatDataClient(cc grpc.ClientConnInterface) FormatDataClient {
	return &formatDataClient{cc}
}

func (c *formatDataClient) DoFormat(ctx context.Context, in *Actionrequest, opts ...grpc.CallOption) (*Actionresponse, error) {
	out := new(Actionresponse)
	err := c.cc.Invoke(ctx, FormatData_DoFormat_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FormatDataServer is the server API for FormatData service.
// All implementations must embed UnimplementedFormatDataServer
// for forward compatibility
type FormatDataServer interface {
	DoFormat(context.Context, *Actionrequest) (*Actionresponse, error)
	mustEmbedUnimplementedFormatDataServer()
}

// UnimplementedFormatDataServer must be embedded to have forward compatible implementations.
type UnimplementedFormatDataServer struct {
}

func (UnimplementedFormatDataServer) DoFormat(context.Context, *Actionrequest) (*Actionresponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoFormat not implemented")
}
func (UnimplementedFormatDataServer) mustEmbedUnimplementedFormatDataServer() {}

// UnsafeFormatDataServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FormatDataServer will
// result in compilation errors.
type UnsafeFormatDataServer interface {
	mustEmbedUnimplementedFormatDataServer()
}

func RegisterFormatDataServer(s grpc.ServiceRegistrar, srv FormatDataServer) {
	s.RegisterService(&FormatData_ServiceDesc, srv)
}

func _FormatData_DoFormat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Actionrequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormatDataServer).DoFormat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FormatData_DoFormat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FormatDataServer).DoFormat(ctx, req.(*Actionrequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FormatData_ServiceDesc is the grpc.ServiceDesc for FormatData service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FormatData_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.FormatData",
	HandlerType: (*FormatDataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoFormat",
			Handler:    _FormatData_DoFormat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "data.proto",
}
